
SELECT 
	 TABLE_NAME 
	,COLUMN_NAME
	,IS_NULLABLE
	,DATA_TYPE
	,NUMERIC_PRECISION
	,NUMERIC_SCALE
FROM INFORMATION_SCHEMA.columns 
WHERE TABLE_NAME LIKE 'T[_]%'
AND DATA_TYPE = 'decimal' 
AND COLUMN_NAME LIKE '%_Lat'
AND COLUMN_NAME NOT LIKE '%_SVLat'
ORDER BY TABLE_NAME, COLUMN_NAME 
